### ISSUE TITLE
settimed crashes

### ISSUE THREAD

**Issue by yegorius** [xyproto/wallutils#10]
`settimed` crashes once in a while https://pastebin.com/Aq1PjEdF
```
> settimed -V
settimed version 5.8.2
```

**Comment by xyproto** [comment]
Thanks for reporting! I'll fix this.

**Comment by xyproto** [comment]
The pastebin log is no longer available, but I believe this might be fixed in version 5.8.3.

Please re-open this issue if not. Thanks.
