### ISSUE TITLE
X Error of failed request:  BadColor (invalid Colormap parameter)

### ISSUE THREAD

**Issue by Torxed** [xyproto/wallutils#13]
Freshly installed computer, manually installed `plasma5-wallpapers-dynamic` beforehand.<br>
Installed `gnome-kde-mojave-dynamic-wallpaper` and then `wallutils`.

Below is output from `settimed mojave-timed`:

```
Setting timed wallpaper: mojave-timed
Searching for wallpapers...
Filtering wallpapers by name...
Using: /usr/share/backgrounds/macOS/mojave-timed.xml
Using the GNOME Timed Wallpaper format
Initial static wallpaper event at 12:00
Window: 17m4s
Cooldown: 17m4s
Filename: /usr/share/backgrounds/macOS/mojave/mojave_dynamic-1200.jpg
Setting /usr/share/backgrounds/macOS/mojave/mojave_dynamic-1200.jpg.
Using the X11 backend.
X Error of failed request:  BadColor (invalid Colormap parameter)
  Major opcode of failed request:  91 (X_QueryColors)
  Resource id in failed request:  0x6002d390
  Serial number of failed request:  7
  Current serial number in output stream:  7
```

Arch Linux (latest from today).
WM: awesome

**Comment by Torxed** [comment]
Does work if you re-run it a few times.. but it produces this, not sure that's normal?:

![2019-11-13-122215_2559x1439_scrot](https://user-images.githubusercontent.com/861439/68759605-ea14f080-0607-11ea-97c2-d42d87187521.png)

**Comment by xyproto** [comment]
Thanks for reporting. I'm planning to rewrite the `settimed` utility.

If you install `feh`, the color conversion should happen correctly. It's a fallback routine for pure old X11 that is failing here.

While the green image looks awesome, I'll fix this, and also test it on awesomewm without having `feh` installed.

**Comment by xyproto** [comment]
I installed Awesome WM to reproduce this issue. I don't get the green image above, but I do get this error:

    X Error of failed request:  BadColor (invalid Colormap parameter)

After installing `feh`, the background image is set correctly.

**Comment by xyproto** [comment]
The latest release will complain if `feh` is not available when using i3 or AwesomeWM, until I can fix the issue with the X11 backend.

It is possible to set `NOFEH=1` to not use `feh`, for debugging, if that should be needed.

Please re-open this issue if there should be further problems with this. Thanks
