### ISSUE TITLE
settimed crashes

### ISSUE THREAD

**Issue by yegorius** [xyproto/wallutils#17]
settimed crashes again
https://pastebin.com/iD3xjh5Z
```
> settimed -V
settimed version 5.8.3
```

**Comment by xyproto** [comment]
Thanks for reporting. Was `feh` installed on your system when the crash happened?

I am in the process of creating a [new X11 backend for setting the wallpaper](
https://github.com/xyproto/xbg), but there are still a few problems related to calling some of the X functions repeatedly, for reasons I'm trying to figure out.

**Comment by yegorius** [comment]
Yes sure, `feh` was present.

**Comment by xyproto** [comment]
I have rewritten the event system and updated the `settimed` command. Could you please check if `settimed` from the `main` branch now works as expected?

**Comment by xyproto** [comment]
There's a new release of wallpaper: 5.10.0. Please re-open this issue if this is still a problem.
