### ISSUE TITLE
No support for modes in setrandom

### ISSUE THREAD

**Issue by tmccombs** [xyproto/wallutils#19]
The setrandom utility doesn't seem to support specifying which mode to use. I would like to use setrandom with the fill mode.

**Comment by xyproto** [comment]
Thanks for the feature request! I will add support for this unless someone beats me to it and creates a pull request. 🙂

**Comment by xyproto** [comment]
I added a `-m` and `--mode` flag in `setrandom` in master.

Please test.

**Comment by ethanmad** [comment]
Hi @xyproto, on a related note I'm looking for the same support in settimed. Is this something you would consider supporting?
