### ISSUE TITLE
Clarify C library dependencies

### ISSUE THREAD

**Issue by kennylevinsen** [xyproto/wallutils#2]
On Fedora 29, wallutils depends on the following non-standard packages for go get to succeed:

- xorg-x11-xbitmaps
- libXcursor-devel
- libXmu-devel (which pulls in libSM, libICE and libXt as well)

It might be helpful to note any compile-time dependencies like this in the readme.

**Comment by xyproto** [comment]
Hi and thanks for reporting! I'll add them to the documentation.

**Comment by xyproto** [comment]
I updated the documentation in a new branch. Does this look correct to you?

https://github.com/xyproto/wallutils/pull/3/commits/6a3fee713f8e0a881e38d630033b3504c254c1b3

**Comment by kennylevinsen** [comment]
Yes, that looks about right for the dependencies I was lacking. There might of course be others that I just happened to already have installed.

**Comment by xyproto** [comment]
OK, thanks for reviewing.
