### ISSUE TITLE
settimed doesn't update wallpaper

### ISSUE THREAD

**Issue by eddsalkield** [xyproto/wallutils#21]
I am currently running `settimed` with `sway` on Fedora.  When initialised, `settimed` sets the wallpaper correctly, but never updates the wallpaper again after that.  When prompted with signal `USR1`, a line is written to the log file but the image is not changed, even hours on.

I am running `settimed` with the following options:
```
settimed /usr/share/backgrounds/eddos/mojave/mojave-timed.stw > /home/edd/wallpaper.log
```
With a `.stw` file containing:
```
stw: 1.0
name: mojave-timed
format: /usr/share/backgrounds/eddos/mojave/mojave_dynamic-%s0.jpg
@00:00-03:00: 000 .. 030
@03:00-06:00: 030 .. 060
@06:00-07:00: 060 .. 070
@07:00-08:00: 070 .. 080
@08:00-09:00: 080 .. 090
@09:00-10:00: 090 .. 100
@10:00-11:00: 100 .. 110
@11:00-12:00: 110 .. 120
@12:00-14:00: 120 .. 140
@14:00-15:00: 140 .. 150
@15:00-16:00: 150 .. 160
@16:00-17:00: 160 .. 170
@17:00-18:00: 170 .. 180
@18:00-19:00: 180 .. 190
@19:00-21:00: 190 .. 210
@21:00-00:00: 210 .. 000
```

Which outputs the following log (the time was 15:30 when prompted with the `USR1` signals):
```
Launching event loop for: /usr/share/backgrounds/eddos/mojave/mojave-timed.stw
Using the Simple Timed Wallpaper format.
Initial transition event at 11:00 (60% complete)
Progress: 36m33s
Up to: 12:00
Window: 1h
Cooldown: 6m
Loop wait: 5s
Transition type: overlay
From filename /usr/share/backgrounds/eddos/mojave/mojave_dynamic-1100.jpg
To filename /usr/share/backgrounds/eddos/mojave/mojave_dynamic-1200.jpg
Setting /usr/share/backgrounds/eddos/mojave/mojave_dynamic-1100.jpg.
Using the Sway backend.
swaymsg output * bg /usr/share/backgrounds/eddos/mojave/mojave_dynamic-1100.jpg stretch
Crossfading between images.
Received signal user defined signal 1
Received signal user defined signal 1
Received signal user defined signal 1
Received signal user defined signal 1
```

Many thanks for your work on this project; I hope that I can start using it properly and not be forced to hack together a pythonic bodge instead.

**Comment by xyproto** [comment]
Thanks for reporting! I'll look into this. `settimed` is the weakest utility included in "wallutils" and I'm in the process of rewriting it.

**Comment by xyproto** [comment]
I have rewritten the event system and updated the `settimed` command. Could you please check if `settimed` from the `main` branch now works as expected?

**Comment by eddsalkield** [comment]
Thanks, I've tested this out and it seems to be working!  I'll run this in the background tomorrow and report back with any difficulties that I experience.

**Comment by xyproto** [comment]
There's a new release of wallpaper: 5.10.0. Please re-open this issue if this should still be a problem.
