### ISSUE TITLE
Unreasonably high memory usage on settimed

### ISSUE THREAD

**Issue by n5q** [xyproto/wallutils#22]
I am currently running settimed (feh backend) which was installed as part of the wallutils package (5.9.0-1) on i3-gaps (4.18.2-2) under Arch Linux. The program works as intended, fading between wallpapers throughout the day however I have noticed that the program uses an unreasonable amount of memory while running in the background regardless of if the program is launched via the i3 config file or manually.

I am using the options `settimed -m zoom /usr/share/backgrounds/gnome/adwaita-timed.xml` which does set the desired wallpaper however it takes up over a gigabyte of memory.
![Screenshot from 2020-08-25 12-05-56](https://user-images.githubusercontent.com/43859271/91199139-73933c00-e6cb-11ea-8f9a-b5e3047743c3.png)

Running the program manually produces the following output
```[nsq@arch ~]$ settimed -m zoom /usr/share/backgrounds/gnome/adwaita-timed.xml 
Launching event loop for: /usr/share/backgrounds/gnome/adwaita-timed.xml
Using the GNOME Timed Wallpaper format
Initial transition event at 08:00 (82% complete)
Progress: 4h7m38s
Up to: 13:00
Window: 5h
Cooldown: 30m
Loop wait: 5s
Transition type: overlay
From filename /usr/share/backgrounds/gnome/adwaita-morning.jpg
To filename /usr/share/backgrounds/gnome/adwaita-day.jpg
Setting /usr/share/backgrounds/gnome/adwaita-morning.jpg.
Using the Feh backend.
feh --bg-fill /usr/share/backgrounds/gnome/adwaita-morning.jpg
Crossfading between images.
Setting /tmp/_settimed.jpg.
Using the Feh backend.
feh --bg-fill /tmp/_settimed.jpg
Activating events in 15m
```

**Comment by xyproto** [comment]
Thanks for reporting! I'll look into this.

**Comment by n5q** [comment]
It appears as if this is only an issue when there is a transitioning wallpaper as it is now using 140mb of memory when not transitioning. Still high memory usage but not as bad as before

**Comment by n5q** [comment]
Possible memory leak when transitioning?

**Comment by xyproto** [comment]
Cross-fading two large images in memory uses some memory, so it's not entirely unreasonable, but I'm planning to both rewrite and profile `settimed`.

**Comment by asif-mahmud** [comment]
i ran into the same problem, but in my case it was using some gb of ram ! i am on archlinux, using wallutils version - 5.9.0-2

**Comment by xyproto** [comment]
I have rewritten the event system and updated the `settimed` command. Could you please check if `settimed` from the `main` branch now works as expected?

**Comment by xyproto** [comment]
This might also be improved when compiling with Go 1.17.

**Comment by xyproto** [comment]
There's a new release of wallpaper: 5.10.0. Please re-open this issue if this should still be a problem.
