### ISSUE TITLE
Unable to run heic-install

### ISSUE THREAD

**Issue by Pound-Hash** [xyproto/wallutils#26]
The following error returns when running `heic-install <file.heic>`:
```
./heic-install: line 39: heic2stw: command not found
```

I installed **wallutils** via the Ubuntu instructions. The command `settimed` works fine.

**Comment by xyproto** [comment]
Thanks for reporting, I'll reproduce the issue on Ubuntu and update the documentation, if needed.

Is `libheif` installed when make is being run?

**Comment by Pound-Hash** [comment]
I don't know how to check that. FYI, I'm on Debian 11.

I ran `dpkg -s libheif` and got these results:

```
libheif-dev:amd64: /usr/share/doc/libheif-dev
libheif1:amd64: /usr/lib/x86_64-linux-gnu/libheif.so.1.11.0
libheif-dev:amd64: /usr/include/libheif/heif_plugin.h
libheif-dev:amd64: /usr/share/doc/libheif-dev/README.md.gz
libheif-dev:amd64: /usr/include/libheif/heif_cxx.h
libheif1:amd64: /usr/share/doc/libheif1
libheif-dev:amd64: /usr/lib/x86_64-linux-gnu/libheif.so
libheif1:amd64: /usr/share/doc/libheif1/changelog.Debian.gz
libheif-dev:amd64: /usr/include/libheif/heif_version.h
libheif-dev:amd64: /usr/share/doc/libheif-dev/changelog.Debian.gz
libheif-dev:amd64: /usr/include/libheif
libheif-dev:amd64: /usr/include/libheif/heif.h
libheif1:amd64: /usr/share/doc/libheif1/copyright
libheif1:amd64: /usr/lib/x86_64-linux-gnu/libheif.so.1
libheif-dev:amd64: /usr/share/doc/libheif-dev/copyright
libheif-dev:amd64: /usr/lib/x86_64-linux-gnu/pkgconfig/libheif.pc
```

**Comment by xyproto** [comment]
I see.

Just a guess, but does `export PATH="/usr/local/bin:$PATH"` make it work?

**Comment by Pound-Hash** [comment]
I use fish (I also tried your script from Bash).

The location /usr/local/bin is already in my $PATH.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by xyproto** [comment]
I installed Debian 11 to test this.

The packages and all the utilities installs fine here, and both `heic-install` and `heic2stw` work fine, and are in the $PATH.

Could you please try the installation instructions for Debian 11 in the README.md file again, and re-open this issue if it is still a problem?

**Comment by Pound-Hash** [comment]
Understood. I'm on Arch now, and it works great. Thanks for the app.

Alan

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
