### ISSUE TITLE
found no working method on labwc compositor

### ISSUE THREAD

**Issue by masrazi** [xyproto/wallutils#28]
I installed wallutils from Arch Linux repository. Both of `setwallpaper` and `setrandom` didn't work. I get this ouput:

```
➜ setwallpaper ~/Pictures/simpledesktop/tardis.png
Could not set wallpaper: found no working method for setting the desktop wallpaper
~ 
✘1 ➜ setrandom ~/Pictures/simpledesktop/             
Found no working method for setting the desktop wallpaper.
```

OS : Artix Linux
Wayland compositor : labwc

It working fine when using sway. Did I miss some configuration for my compositor? Or it didn't support labwc?

**Comment by xyproto** [comment]
Thanks for reporting! It does not support labwc yet. It seems like every Wayland compositor has a different way of setting the wallpaper, while the X window managers have more common methods.

**Comment by xyproto** [comment]
I added code to `main` that works under labwc here.

Please check if it also works on your system.

It requires `swaybg` and `pkill` to work.
