### ISSUE TITLE
settimed not works on hyprland

### ISSUE THREAD

**Issue by hyq12358** [xyproto/wallutils#29]
WM:
https://github.com/hyprwm/Hyprland

`settimed` log:

Setting timed wallpaper: mu
Searching for wallpapers...
Filtering wallpapers by name...
Using: /usr/share/backgrounds/mu/mu.stw
Using the Simple Timed Wallpaper format.
Attaching to ongoing static wallpaper event that started at 18:00
Window: 6h
Cooldown: 6h
Filename: /usr/share/backgrounds/mu/03.jpg
Setting /usr/share/backgrounds/mu/03.jpg.
Could not set wallpaper: found no working method for setting the desktop wallpaperSetting timed wallpaper: mu-timed
Searching for wallpapers...
Filtering wallpapers by name...
Could not find timed wallpaper: mu-timed

**Comment by xyproto** [comment]
Thanks for reporting!

Looking at [the Hyprland source code](https://github.com/hyprwm/Hyprland/blob/c40ef59a3570e2d80a0b15131e6964c3c5e14408/src/render/OpenGL.cpp) and searching the repository for "wall", it does not appear like Hyprland supports setting the wallpaper at runtime. I could not find configuration options for this either.

Please re-open this issue once Hyprland supports setting the wallpaper at runtime, or if I've misunderstood how Hyprland currently works.
