### ISSUE TITLE
Please add support for Hyprland

### ISSUE THREAD

**Issue by hyq12358** [xyproto/wallutils#30]
Hyprland
https://github.com/hyprwm/Hyprland

**Comment by xyproto** [comment]
Apparently, Hyprland does not support changing the wallpaper after Hyprland has been started.

Please report this to the Hyprland developers in the form of a feature request.

Please re-open this issue if I should have misunderstood anything.

**Comment by xyproto** [comment]
ref https://github.com/hyprwm/Hyprland/issues/304
