### ISSUE TITLE
settimed fails to set transition wallapaper

### ISSUE THREAD

**Issue by yegorius** [xyproto/wallutils#7]
settimed correctly sets wallpaper during the launch, but crashes in the next 20 minutes or so:
```
Crossfading between images.
Window: 20m
Cooldown: 2m
Loop wait: 5s
Transition type: overlay
From filename /usr/share/backgrounds/gnome/mojave/mojave_dynamic-1000.jpg
To filename /usr/share/backgrounds/gnome/mojave/mojave_dynamic-1100.jpg
Crossfading between images.
Setting /tmp/gnometimed_crossfade.png.
Using the Feh backend.
feh --bg-scale /tmp/gnometimed_crossfade.png
Setting /tmp/gnometimed_crossfade.png.
Using the Feh backend.
feh --bg-scale /tmp/gnometimed_crossfade.png
failed: feh --bg-scale /tmp/gnometimed_crossfade.png failed to run
Using the X11 backend.
convert /tmp/gnometimed_crossfade.png /tmp/_setwallpaper.xbm
failed: feh --bg-scale /tmp/gnometimed_crossfade.png failed to run
Using the X11 backend.
convert /tmp/gnometimed_crossfade.png /tmp/_setwallpaper.xbm
Setting /tmp/gnometimed_crossfade.png.
Using the Feh backend.
feh --bg-scale /tmp/gnometimed_crossfade.png
failed: feh --bg-scale /tmp/gnometimed_crossfade.png failed to run
Using the X11 backend.
convert /tmp/gnometimed_crossfade.png /tmp/_setwallpaper.xbm
malloc(): unsorted double linked list corrupted
SIGABRT: abort
...
```
If I then try to run feh on `/tmp/gnometimed_crossfade.png `:
```
feh --bg-scale /tmp/gnometimed_crossfade.png 
libpng error: bad adaptive filter value
feh WARNING: /tmp/gnometimed_crossfade.png - No Imlib2 loader for that file format
feh ERROR: Unable to load image /tmp/gnometimed_crossfade.png
```
OS: Arch Linux
WM: i3

**Comment by xyproto** [comment]
Thanks for reporting! I will look into this. The X11 backend is the most fragile of all the available backend. It was surprising to me that the feh backend failed with the cross fade image. I will fix this.

**Comment by xyproto** [comment]
I implemented support for writing the XBM and XPM image file formats, as steps in solving this issue:

* [xbm](https://github.com/xyproto/xbm)
* [xpm](https://github.com/xyproto/xpm)

My next plan is to write directly to xpm and and skip using `feh`.

**Comment by xyproto** [comment]
I added functionality to `x11.go` and `xwallpaper.h` for setting XPM images as the background image, for X11, instead of using `feh` or the XBM format. This could be improved further by not writing to a temporary file and setting the image data directly through the X11-related C-functions.

However, images with too many colors may still be an issue.

I also need to test this new functionality a bit more.

**Comment by xyproto** [comment]
I created the [palgen](https://github.com/xyproto/palgen) package and made some changes to the [xpm](https://github.com/xyproto/xpm). It can now reduce the number of colors when converting images to `.xpm`. It could probably be both faster and more robust, but it should remove the issue of images having too many colors when setting `.xpm` images as wallpapers.

Please test the latest `master` of `wallutils` and see if the issue has now been resolved.

I'm also planning to do some more testing on various window managers for X.

**Comment by xyproto** [comment]
I just tested with i3, and it works best with the `feh` method.

Since your installation says:

```
feh WARNING: /tmp/gnometimed_crossfade.png - No Imlib2 loader for that file format
feh ERROR: Unable to load image /tmp/gnometimed_crossfade.png
```

Perhaps your installation of `imlib2` has been compiled without support for PNG files?

Could you please try reinstalling `feh` and/or imlib2, or possibly install any missing packages that could be related?

**Comment by xyproto** [comment]
After looking into this error: `libpng error: bad adaptive filter value`, I think there may be something wrong with the `png` image itself, possibly a concurrency issue, if the writing of the png image was aborted somehow.

I will try to reproduce the error by running the same command as you did.

**Comment by yegorius** [comment]
I have the latest version of feh and imlib2 from Arch and imlib2 is compiled with png support. Anyway, here is the fresh log [output](https://gist.github.com/yegorius/aa6790044451f1f7b36236d4ed7f5cdc)

**Comment by xyproto** [comment]
Thanks for the log output! I looked into this, and there is something wrong with the function that performs the cross-fade between two images, in relation to concurrency, resulting in half-written images. I will fix this.

**Comment by xyproto** [comment]
I have made several changes related to the cross-fade functionality.

* Now using [bild](https://github.com/anthonynsimon/bild) for the crossfade (blend).
* Using a mutex when writing the temporary image, to make sure it can write it in peace.

Please test the latest `master` and see if it fixes this issue. Thanks!

**Comment by xyproto** [comment]
Now there are other issues. The Mojave wallpaper events are not correct. I'll have to look into this as well.

**Comment by xyproto** [comment]
I think this bug is fixed. However, issue #9 remains. Please re-open if there should be further issues with this.
